---
- name: Apply common configuration and hardening
  hosts: all
  become: yes
  gather_facts: no  # Disable default fact gathering

  roles:
    - role: system_update
    - role: chrony_configuration
    - role: apache_configuration
    - role: ssh_hardening
