---
- name: Update YUM package list
  yum:
    name: '*'
    state: latest

- name: Upgrade all YUM packages
  yum:
    name: '*'
    state: latest

- name: Ensure YUM mirrors are up-to-date
  shell: yum clean all && yum makecache
